.TH crypto 6 "crypto  1.1.2" "Ericsson Utvecklings AB" "ERLANG APPLICATION DEFINITION"
.SH APPLICATION
crypto \- The Crypto Application
.SH DESCRIPTION
.LP
This chapter describes the application Crypto in OTP, which provides message digests MD5 and SHA, and CBC-DES encryption and decryption\&. 
.LP
The purpose of this application is to provide message digest and DES encryption for SMNPv3\&. 
.LP


.SH Configuration
.LP
The following environment configuration parameters are defined for the Crypto application\&. Refer to application(3) for more information about configuration parameters\&. 
.RS 2
.TP 4
.B
\fIdebug = true | false <optional>\fR:
Causes debug information to be written to standard error or standard output\&. Default is \fIfalse\fR\&. 
.RE
.SH SEE ALSO
.LP
application(3) 
.SH AUTHOR
.nf
Peter Hogfeldt - support@erlang.ericsson.se
.fi
