.TH appmon 3 "appmon  2.0.1" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
appmon \- A graphical node and application process tree viewer\&.
.SH DESCRIPTION
.LP
The application monitor Appmon is a graphical utility used to supervise applications executing either locally or on remote nodes\&. The process tree of an application can furthermore be monitored\&.

.SH EXPORTS
.LP
.B
start()
.br
.RS
.LP
\fIstart/0\fR starts Appmon\&.
.RE
.SH See Also
.LP
Appmon User\&'s Guide
.SH AUTHOR
.nf
Gunilla Hugosson - support@erlang.ericsson.se
.fi
