.TH gs 3 "gs  1.3.7" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
gs \-  The Graphics System for Erlang\&. 
.SH DESCRIPTION
.LP
The Graphics System (GS) for Erlang is easy to learn and was designed to be portable to many different platforms\&.

.SH SEE ALSO
.LP
Refer to the GS User\&'s Guide for a complete description of GS\&. 
.SH AUTHOR
.nf
Klas Eriksson - support@erlang.ericsson.se
.fi
