.TH mod_log 3 "inets  2.5.3" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
mod_log \- Standard logging using the "Common Logfile Format" and text files\&. 
.SH DESCRIPTION
.LP
This module makes it possible to log all incoming requests to an access log file\&. The de-facto standard Common Logfile Format is used for this purpose\&. There are numerous statistics programs available to analyze Common Logfile Format\&. The Common Logfile Format looks as follows: 
.LP
\fIremotehost rfc931 authuser [date] "request" status bytes\fR 
.RS 2
.TP 4
.B
\fIremotehost\fR:
Remote hostname
.TP 4
.B
\fIrfc931\fR:
The client\&'s remote username (RFC 931)\&.
.TP 4
.B
\fIauthuser\fR:
The username with which the user authenticated himself\&.
.TP 4
.B
\fI[date]\fR:
Date and time of the request (RFC 1123)\&.
.TP 4
.B
\fI"request"\fR:
The request line exactly as it came from the client (RFC 1945)\&.
.TP 4
.B
\fIstatus\fR:
The HTTP status code returned to the client (RFC 1945)\&.
.TP 4
.B
\fIbytes\fR:
The content-length of the document transferred\&.
.RE
.LP
This module furthermore supports the use of an error log file to record internal server errors\&. The error log format is more ad hoc than Common Logfile Format, but conforms to the following syntax: 
.LP
\fI[date]\fR access to \fIpath\fR failed for \fIremotehost\fR, reason: \fIreason\fR 

.SH DIRECTIVE: "ErrorLog"
.LP
\fISyntax:\fR \fIErrorLog\fR filename
.br
 \fIDefault:\fR - None -
.br
 \fIModule:\fR mod_log(3) 
.LP
\fIErrorLog\fR defines the \fIfilename\fR of the error log file to be used to log server errors\&. If the \fIfilename\fR does not begin with a slash (\fI/\fR) it is assumed to be relative to the ServerRoot, for example: 

.nf
ErrorLog logs/error_log_8080
.fi
.LP
and errors will be logged in the server root($SERVER_ROOT/logs/error_log_8080) space\&. 
.SH DIRECTIVE: "TransferLog"
.LP
\fISyntax:\fR \fITransferLog\fR filename
.br
 \fIDefault:\fR - None -
.br
 \fIModule:\fR mod_log(3) 
.LP
\fITransferLog\fR defines the \fIfilename\fR of the access log file to be used to log incoming requests\&. If the \fIfilename\fR does not begin with a slash (\fI/\fR) it is assumed to be relative to the ServerRoot\&. For example: 

.nf
TransferLog logs/access_log_8080
.fi
.LP
and errors will be logged in the server root($SERVER_ROOT/logs/access_log_8080) space\&. 
.SH EWSAPI MODULE INTERACTION
.LP
Uses the following EWSAPI interaction data, if available: 
.RS 2
.TP 4
.B
\fI{remote_user, RemoteUser}\fR:
as defined in mod_auth(3)\&.
.RE
.LP
This module furthermore exports a batch of functions to be used by other EWSAPI modules: 
.SH EXPORTS
.LP
.B
error_log(Socket,SocketType,ConfigDB,Date,Reason) -> ok | no_error_log
.br
.RS
.TP
Types
Socket = socket()
.br
SocketType = ip_comm | ssl
.br
ConfigDB = config_db()
.br
Date = Reason = string()
.br
.RE
.RS
.LP
\fIerror_log/5\fR logs an error in a log file\&. \fISocket\fR is a handler to a socket of type \fISocketType\fR and \fIconfig_db()\fR is the server config file in ETS table format as described in httpd(3)\&. \fIDate\fR is a RFC 1123 date string as generated by httpd_util:rfc1123_date/0\&. 
.RE
.SH SEE ALSO
.LP
httpd(3), mod_auth(3), mod_security(3), mod_disk_log(3) 
.SH AUTHOR
.nf
Joakim Grebeno  - support@erlang.ericsson.se
.fi
