.TH mod_disk_log 3 "inets  2.5.3" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
mod_disk_log \- Standard logging using the "Common Logfile Format" and disk_log(3)\&. 
.SH DESCRIPTION
.LP
This module uses \fIdisk_log(3)\fR to make it possible to log all incoming requests to an access log file\&. The de-facto standard Common Logfile Format is used for this purpose\&. There are numerous statistic programs available to analyze Common Logfile Format log files\&. The Common Logfile Format looks as follows: 
.LP
\fIremotehost rfc931 authuser [date] "request" status bytes\fR 
.RS 2
.TP 4
.B
\fIremotehost\fR:
Remote hostname (or IP number if the DNS hostname is not available)\&.
.TP 4
.B
\fIrfc931\fR:
The client\&'s remote username (RFC 931)\&.
.TP 4
.B
\fIauthuser\fR:
The username with which the user has authenticated himself\&.
.TP 4
.B
\fI[date]\fR:
Date and time of the request (RFC 1123)\&.
.TP 4
.B
\fI"request"\fR:
The request line exactly as it came from the client (RFC 1945)\&.
.TP 4
.B
\fIstatus\fR:
The HTTP status code returned to the client (RFC 1945)\&.
.TP 4
.B
\fIbytes\fR:
The content-length of the document transferred\&.
.RE
.LP
This module furthermore uses \fIdisk_log(3)\fR to support the use of an error log file to record internal server errors\&. The error log format is more ad hoc than Common Logfile Format, but conforms to the following syntax: 
.LP
\fI[date]\fR access to \fIpath\fR failed for \fIremotehost\fR, reason: \fIreason\fR 

.SH DIRECTIVE: "ErrorDiskLog"
.LP
\fISyntax:\fR \fIErrorDiskLog\fR filename
.br
 \fIDefault:\fR - None -
.br
 \fIModule:\fR mod_disk_log(3) 
.LP
\fIErrorDiskLog\fR defines the \fIfilename\fR of the \fIdisk_log(3)\fR error log file to be used to log server errors\&. If the \fIfilename\fR does not begin with a slash (\fI/\fR) it is assumed to be relative to the ServerRoot, for example: 

.nf
ErrorDiskLog logs/error_disk_log_8080
.fi
.LP
and errors will be logged in the server root($SERVER_ROOT/logs/error_disk_log_8080) space\&. 
.SH DIRECTIVE: "ErrorDiskLogSize"
.LP
\fISyntax:\fR \fIErrorDiskLogSize\fR max-bytes max-files
.br
 \fIDefault:\fR \fIErrorDiskLogSize 512000 8\fR
.br
 \fIModule:\fR mod_disk_log(3) 
.LP
\fIErrorDiskLogSize\fR defines the properties of the \fIdisk_log(3)\fR error log file\&. The \fIdisk_log(3)\fR error log file is of type \fIwrap log\fR and \fImax-bytes\fR will be written to each file and \fImax-files\fR will be used before the first file is truncated and reused\&. 
.SH DIRECTIVE: "TransferDiskLog"
.LP
\fISyntax:\fR \fITransferDiskLog\fR filename
.br
 \fIDefault:\fR - None -
.br
 \fIModule:\fR mod_disk_log(3) 
.LP
\fITransferDiskLog\fR defines the \fIfilename\fR of the \fIdisk_log(3)\fR access log file which logs incoming requests\&. If the \fIfilename\fR does not begin with a slash (\fI/\fR) it is assumed to be relative to the ServerRoot, for example: 

.nf
TransferDiskLog logs/transfer_disk_log_8080
.fi
.LP
and errors will be logged in the server root($SERVER_ROOT/logs/transfer_disk_log_8080) space\&. 
.SH DIRECTIVE: "TransferDiskLogSize"
.LP
\fISyntax:\fR \fITransferDiskLogSize\fR max-bytes max-files
.br
 \fIDefault:\fR \fITransferDiskLogSize 512000 8\fR
.br
 \fIModule:\fR mod_disk_log(3) 
.LP
\fITransferDiskLogSize\fR defines the properties of the \fIdisk_log(3)\fR access log file\&. The \fIdisk_log(3)\fR access log file is of type \fIwrap log\fR and \fImax-bytes\fR will be written to each file and \fImax-files\fR will be used before the first file is truncated and reused\&. 
.SH EWSAPI MODULE INTERACTION
.LP
Uses the following EWSAPI interaction data, if available: 
.RS 2
.TP 4
.B
\fI{remote_user, RemoteUser}\fR:
as defined in mod_auth(3)\&.
.RE
.LP
This module furthermore exports a batch of functions to be used by other EWSAPI modules: 
.SH EXPORTS
.LP
.B
error_log(Socket,SocketType,ConfigDB,Date,Reason) -> ok | no_error_log
.br
.RS
.TP
Types
Socket = socket()
.br
SocketType = ip_comm | ssl
.br
ConfigDB = config_db()
.br
Date = Reason = string()
.br
.RE
.RS
.LP
\fIerror_log/5\fR uses \fIdisk_log(3)\fR to log an error in the error log file\&. \fISocket\fR is a handler to a socket of type \fISocketType\fR and \fIconfig_db()\fR is the server config file in ETS table format as described in httpd(3)\&. \fIDate\fR is a RFC 1123 date string as generated by httpd_util:rfc1123_date/0\&. 
.RE
.SH SEE ALSO
.LP
httpd(3), mod_auth(3), mod_security(3), mod_log(3) 
.SH AUTHOR
.nf
Joakim Grebeno  - support@erlang.ericsson.se
.fi
