.TH orddict 3 "stdlib  1.9.1" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
orddict \- Key-Value Dictionary as Ordered List
.SH DESCRIPTION
.LP
\fIOrddict\fR implements a \fIKey\fR - \fIValue\fR dictionary\&. An \fIorddict\fR is a representation of a dictionary, where a list of pairs is used to store the keys and values\&. The list is ordered after the keys\&. 
.LP
This module provides exactly the same interface as the module \fIdict\fR but with a defined representation\&. 

.SH AUTHOR
.nf
Robert Virding - support@erlang.ericsson.se
.fi
