.TH ordsets 3 "stdlib  1.9.1" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
ordsets \- Functions for Manipulating Sets as Ordered Lists 
.SH DESCRIPTION
.LP
Sets are collections of elements with no duplicate elements\&. An \fIordset\fR is a representation of a set, where an ordered list is used to store the elements of the set\&. An ordered list is more efficient than an unordered list\&. 
.LP
This module provides exactly the same interface as the module \fIsets\fR but with a defined representation\&. 

.SH AUTHOR
.nf
Robert Virding - support@erlang.ericsson.se
.fi
