.TH pg 3 "stdlib  1.9.1" "Ericsson Utvecklings AB" "ERLANG MODULE DEFINITION"
.SH MODULE
pg \- Distributed, Named Process Groups
.SH DESCRIPTION
.LP
This (experimental) module implements process groups\&. A process group is a group of processes that can be accessed by a common name\&. For example, a group named \fIfoobar\fR can include a set of processes as members of this group and they can be located on different nodes\&.
.LP
When messages are sent to the named group, all members of the group receive the message\&. The messages are serialized\&. If the process \fIP1\fR sends the message \fIM1\fR to the group, and process \fIP2\fR simultaneously sends message \fIM2\fR, then all members of the group receive the two messages in the same order\&. If members of a group terminate, they are automatically removed from the group\&.
.LP
This module is not complete\&. The module is inspired by the ISIS system and the causal order protocol of the ISIS system should also be implemented\&. At the moment, all messages are serialized by sending them through a group master process\&.

.SH EXPORTS
.LP
.B
create(PgName)
.br
.RS
.LP
Creates an empty group named \fIPgName\fR on the current node\&. 
.RE
.LP
.B
create(PgName, Node)
.br
.RS
.LP
Creates an epmty group on the node \fINode\fR\&. 
.RE
.LP
.B
join(PgName, Pid)
.br
.RS
.LP
Joins the Pid \fIPid\fR to the process group \fIPgName\fR\&. 
.RE
.LP
.B
send(Pgname, Message)
.br
.RS
.LP
Sends the tuple \fI{pg_message, From, PgName, Message}\fR to all members of the process group\&. 
.RE
.LP
.B
esend(PgName, Mess)
.br
.RS
.LP
Sends the tuple \fI{pg_message, From, PgName, Message}\fR to all members of the process group, except the current node\&. 
.RE
.LP
.B
members(PgName)
.br
.RS
.LP
Returns a list of the current members in the process group\&. 
.RE
.SH AUTHOR
.nf
 Claes Wikstrom - support@erlang.ericsson.se
.fi
