.TH werl 1 "erts  5.0.1" "Ericsson Utvecklings AB" "USER COMMANDS"
.SH NAME
werl \- The Erlang Emulator
.SH DESCRIPTION
.LP
On Windows 95/NT, the preferred way to start the Erlang system is: 
.LP
\fIwerl <script-flags> <user-flags>\fR 
.LP
This will start Erlang in its own window, which is nice for interactive use (command-line editing will work and there are scrollbars)\&. All flags except the \fI-oldshell\fR flag work as in \fIerl\fR\&. 
.LP
In cases there you want to redirect standard input and/or standard output or use Erlang in a pipeline, the \fIwerl\fR is not suitable, and the \fIerl\fR program should be used instead\&. 

.SH AUTHOR
.nf
Joe Armstrong - support@erlang.ericsson.se
.fi
